# Generated by Django 5.0 on 2023-12-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('user_phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery_exception', 'Delivery Exception'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_status_app.card')),
            ],
        ),
    ]
